### ISSUE TITLE
After a Home Assistant upgrade, maintenance checks cause an error.

### ISSUE THREAD

**Issue by cetiusrex** [jeremywillans/ha-rest980-roomba#17]
After upgrading to the latest Home Assistant 2020.12 I started having the following errors causing the maintenance checks to fail:

home-assistant   | 2020-12-14 15:15:00 ERROR (MainThread) [homeassistant.components.automation.vacuum_maintenance_check] While executing automation automation.vacuum_maintenance_check
home-assistant   | Traceback (most recent call last):
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 353, in async_render
home-assistant   |     render_result = compiled.render(kwargs)
home-assistant   |   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
home-assistant   |     self.environment.handle_exception()
home-assistant   |   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
home-assistant   |     reraise(*rewrite_traceback_stack(source=source))
home-assistant   |   File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
home-assistant   |     raise value.with_traceback(tb)
home-assistant   |   File "<template>", line 1, in top-level template code
home-assistant   |   File "/usr/local/lib/python3.8/site-packages/jinja2/runtime.py", line 545, in __next__
home-assistant   |     rv = next(self._iterator)
home-assistant   |   File "<template>", line 1, in template
home-assistant   | TypeError: '<' not supported between instances of 'NoneType' and 'float'
home-assistant   |
home-assistant   | The above exception was the direct cause of the following exception:
home-assistant   |
home-assistant   | Traceback (most recent call last):
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 165, in async_prepare_call_from_config
home-assistant   |     domain_service = domain_service.async_render(variables)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 355, in async_render
home-assistant   |     raise TemplateError(err) from err
home-assistant   | homeassistant.exceptions.TemplateError: TypeError: '<' not supported between instances of 'NoneType' and 'float'
home-assistant   |
home-assistant   | The above exception was the direct cause of the following exception:
home-assistant   |
home-assistant   | Traceback (most recent call last):
home-assistant   |   File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 404, in async_trigger
home-assistant   |     await self.action_script.async_run(
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1026, in async_run
home-assistant   |     await asyncio.shield(run.async_run())
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 242, in async_run
home-assistant   |     await self._async_step(log_exceptions=False)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 250, in _async_step
home-assistant   |     await getattr(
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 429, in _async_call_service_step
home-assistant   |     domain, service_name, service_data = service.async_prepare_call_from_config(
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 168, in async_prepare_call_from_config
home-assistant   |     raise HomeAssistantError(
home-assistant   | homeassistant.exceptions.HomeAssistantError: Error rendering service name template: TypeError: '<' not supported between instances of 'NoneType' and 'float'

I'm using the latest vacuum.yaml from your repo. Please let me know if you need more information or details.

Thank you,
Cetius

**Comment by cetiusrex** [comment]
Please disregard this issue. I figured out the problem and it has nothing to do with the 2012.12 upgrade. It is a MQTT issue. I'm going to close it. Thank you!
