### ISSUE TITLE
Willans Hass.io Add-ons: rest980 Docker Image failed

### ISSUE THREAD

**Issue by cowpuncher1871** [jeremywillans/ha-rest980-roomba#22]
Hi Jeremy,
get this when I try to install rest980 Docker Image:

any idea?

thanks for your help

21-03-04 09:12:31 INFO (SyncWorker_1) [supervisor.docker.interface] Restarting homeassistant/qemux86-64-homeassistant
21-03-04 09:12:40 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
21-03-04 09:14:22 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
21-03-04 09:38:58 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 'NoneType' object has no attribute 'is_file'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 100, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 182, in install
    await addon.instance.install(store.version, store.image)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 32, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 491, in _install
    self._build(version)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 500, in _build
    build_env = AddonBuild(self.coresys, self.addon)
  File "/usr/src/supervisor/supervisor/addons/build.py", line 32, in __init__
    super().__init__(
  File "/usr/src/supervisor/supervisor/utils/common.py", line 59, in __init__
    self.read_data()
  File "/usr/src/supervisor/supervisor/utils/common.py", line 72, in read_data
    if self._file.is_file():
AttributeError: 'NoneType' object has no attribute 'is_file'

**Comment by JeroenDeckers** [comment]
I have the same thing

**Comment by jeremywillans** [comment]
Per [this](https://community.home-assistant.io/t/supervisor-2021-3-0-local-add-ons-nonetype-object-has-no-attribute-is-file/286350/2) I have added a build.yaml file to each directory.

Can you test and see if this fixes it?

**Comment by JeroenDeckers** [comment]
issue solved

**Comment by cowpuncher1871** [comment]
issue solved, thanks for the fast answer!
