### ISSUE TITLE
Connection refused error?

### ISSUE THREAD

**Issue by FridayGitHub** [jeremywillans/ha-rest980-roomba#25]
Hi, I have been following the guide and both trough docker command and add-on I get similar error. Roomba is set to "pairing" with wifi light flashing and the IP is correct. I have also standard Roomba Integration up and running with no issue, however cannot retrieve the ID and password using add-on. Here's error:

> dorita980@3.1.7 getpassword /usr/src/app
> node ./bin/getpassword.js
Make sure your robot is on the Home Base and powered on (green lights on). Then press and hold the HOME button on your robot until it plays a series of tones (about 2 seconds). Release the button and your robot will flash WIFI light.
This step will continue in 10 seconds...
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: connect ECONNREFUSED 192.168.1.4:8883
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
npm ERR! Linux 5.10.17-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "getpassword"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! dorita980@3.1.7 getpassword: `node ./bin/getpassword.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dorita980@3.1.7 getpassword script 'node ./bin/getpassword.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dorita980 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/getpassword.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dorita980
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dorita980
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

**Comment by jeremywillans** [comment]
> I have also standard Roomba Integration up and running with no issue
Firstly, these dont play nice togerher, either use the HA version or this one.

If you already have the BLID/Password, then why are you running getpassword?

**Comment by FridayGitHub** [comment]
Hi, Thanks for response. In ha integration I do not see BLID and password, is there a way to read it? I’m running get password to get an integration that allows map processing in HA, unless with standard integration this would also be possible?

**Comment by jeremywillans** [comment]
I believe the built in HA integration does provide coordinates. If you took some of the automations to log the data into the log file and leveraged the php-nginx add-on to publish the image file the in theory this would work.

If you want to get the password for my full integration, i would suggest turning off the default HA integration when trying to get the password (and make sure the app is closed)

**Comment by jeremywillans** [comment]
Bump

**Comment by jeremywillans** [comment]
final bump
