### ISSUE TITLE
rest980 start and nginx image.php issues - different to #24

### ISSUE THREAD

**Issue by BackedUpBooty** [jeremywillans/ha-rest980-roomba#27]
Hey there, thanks for all your work in figuring this out, I'm really looking forward to getting my set up working! I need a little help though please...

My system: Synology VM, running HA Supervised
HA accessible on local 192.168.1.105:8123 and at https://ha.mydomain.com

**Rest980 issue:**
I downloaded your repository to the Add-ons, and installed them directly from there. I managed to get through to step 8 of your walkthrough before noticing something wasn't right. On initial startup of rest980, all was good. I was able to start a clean with the roomba, and then access the state to grab region_ids for the secrets.yaml. 

Everything else going smoothly, I'd updated the top parts of image.php and set the card in lovelace, however all info was coming back as 'unknown'. I restarted rest980, and got the below:

```
> rest980@2.1.0 start /usr/src/app
> node ./bin/www
/usr/src/app/node_modules/dorita980/lib/v2/local.js:33
    throw e;
    ^
Error: Connection refused: Identifier rejected
    at MqttClient._handleConnack (/usr/src/app/node_modules/mqtt/lib/client.js:920:15)
    at MqttClient._handlePacket (/usr/src/app/node_modules/mqtt/lib/client.js:350:12)
    at work (/usr/src/app/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/usr/src/app/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/usr/src/app/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/src/app/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/usr/src/app/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at TLSSocket.ondata (_stream_readable.js:558:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:559:20)
npm ERR! Linux 5.10.42
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! rest980@2.1.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rest980@2.1.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rest980 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rest980
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rest980
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
```

Rest Configuration is set to the same BLID, password and IP as before. I've confirmed that they haven't changed, same with version 2. I'd already removed the HA native roomba add-ons and the iRobot app on my phone is not active. 

I've since uninstalled and reinstalled the add-on, and am getting the same printout.

**PHP issue:**
I've adjusted the following parameters 
```
$vacuum_log = 'http://192.168.1.105:3001/vacuum.log'; # Could also be HTTPS
$set_first_coordinate = 0; # Ability to skip initial coordinate(s) if incorrect data logged
$overlay_image = 'floor.png'; # Background Layer
$overlay_walls = false; # Allows overlaying of walls, used in fill mode to cover 'spray'
$walls_image = 'walls.png'; # Walls Image must contain transparent floor
$show_stuck_positions = true; 
$line_thickness = 2; # Default 2, Set to ~60 for Fill Mode
$map_width = 1050; # Ensure overlay and wall images match this size
$map_height = 900; # Ensure overlay and wall images match this size
$x_offset = 220;
$y_offset = 220;
$flip_vertical = false;
$flip_horizontal = false;
$rotate_angle = 0; # Allows rotating of the roomba lines
$x_scale=1.00; # Allows scaling of roomba x lines
$y_scale=1.00; # Allows scaling of roomba y lines
$ha_rest980 = 'http://192.168.1.105:8123/api/states/sensor.rest980';
$ha_token = '[REDACTED]';
$ha_timezone = 'Asia/Tokyo'; # Supported Timezones https://www.php.net/manual/en/timezones.php
$ha_text_delimiter = " \n"; # How text is displayed on the map top " \n" --> New Line ## " |" --> Show on one line
```
When I go to `http://192.168.1.105:3001/vacuum.log` the log downloads - not a problem, I've seen there's a FAQ for this, I mention it to show that the paths work. But when I go to `http://192.168.1.105:3001/image.php` the printout is `No Coordinates found in file, is it reachable and populated? Log file - http://192.168.1.105:3001/vacuum.log?`. I can't find why this output is being created, any thoughts?

Cheers!

**Comment by BackedUpBooty** [comment]
Maybe I just wasn't giving it enough time or something, but it's now working again. Closing issue.
