### ISSUE TITLE
Errors trying to connect and get password.

### ISSUE THREAD

**Issue by BRoadifer** [jeremywillans/ha-rest980-roomba#62]
I've been trying to get this to work for a while now... Figured I'd ask here.

I have an 7i+  
Software shows 22.52.5

My config I have my IP address and for Firmware 22.  Not sure if that is correct though.

I noticed that the script says it will continue after 10 seconds, but it never does.

> dorita980@3.1.7 getpassword /usr/src/app
> node ./bin/getpassword.js
Make sure your robot is on the Home Base and powered on (green lights on). Then press and hold the HOME button on your robot until it plays a series of tones (about 2 seconds). Release the button and your robot will flash WIFI light.
This step will continue in 10 seconds...
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: connect EHOSTUNREACH 192.168.1.79:8883
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
npm ERR! Linux 6.1.34
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "getpassword"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! dorita980@3.1.7 getpassword: `node ./bin/getpassword.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dorita980@3.1.7 getpassword script 'node ./bin/getpassword.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dorita980 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/getpassword.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dorita980
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dorita980
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

**Comment by BRoadifer** [comment]
Thanks for the reply... I use Home Assistant OS. Is there a way to do this through HACS?
