### ISSUE TITLE
Error when executing docker run

### ISSUE THREAD

**Issue by Tokn59** [jeremywillans/ha-rest980-roomba#72]
When executing the following : 

run --name rest980 -e BLID=************************ -e PASSWORD=***************** -e ROBOT_IP=192.168.1.74 -e FIRMWARE_VERSION=2 -p 3000:3000 koalazak/rest980:latest

I get Error : Error response from daemon: driver failed programming external connectivity on endpoint rest980 (68bf65ec9dbec368600a893459155a094efb3642814959db4d75a873b8bacebd): Bind for 0.0.0.0:3000 failed: port is already allocated.

It seems port 3000 is already in use by another addon (Doubletake). Can I simply use any other port ?

THANK YOU !!!!

**Comment by xnemesis** [comment]
Have you tried changing the ports in the addon or in the docker? There's no reason any port can't work as 3000 isn't an irobot port, just an addon port.

**Comment by jeremywillans** [comment]
As what @xnemesis said, you can change the binding to a different port

-p "3005:3000" for example which will map your computers port of 3005 to the container port of 3000

Just make sure you reference 3005 in the other yaml files

**Comment by Tokn59** [comment]
Thank you !!!! I have changed to port 3005 and so I can "see" the robot data on this page : 

http://192.168.1.15:3005/api/local/info/state 

So that part is OK. But still I get the same error after starting this docker command :

WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
GET / 200 33.924 ms - 89
GET /favicon.ico 200 11.450 ms - 15406
GET /api/state 404 12.839 ms - 136
**Error: Endpoint not found.**
    at /usr/src/app/app.js:62:13
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at /usr/src/app/node_modules/express/lib/router/index.js:635:15
    at next (/usr/src/app/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/usr/src/app/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/src/app/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at /usr/src/app/node_modules/express/lib/router/index.js:635:15
    at next (/usr/src/app/node_modules/express/lib/router/index.js:260:14)
    at jsonParser (/usr/src/app/node_modules/body-parser/lib/types/json.js:110:7)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
GET /api/local/info/state 200 118.002 ms - 4563

**Comment by jeremywillans** [comment]
`GET /api/state 404 12.839 ms - 136`

something is trying to reach this URL which is not correct - check and see if its in your configuration somewhere?

**Comment by Tokn59** [comment]
Also I noticed that I need to run te following according to the documentation : 

docker run -name php-nginx -p 3001:8080 -v /<HA_CONFIG>/roomba:/app -e NGINX_WEBROOT=/app webhippie/php-nginx:latest

Not sure what <HA-CONFIG> should be. I used the following : 

docker run -name php-nginx -p 3001:8080 -v /**192.168.1.15:8443**/roomba:/app -e NGINX_WEBROOT=/app webhippie/php-nginx:latest

I get this error : 

**unknown shorthand flag: 'n' in -name
See 'docker run --help'.**

**Comment by jeremywillans** [comment]
You need to use two dashes for name

`--name`

**Comment by Tokn59** [comment]
the path to the HA folder ... In what format should that be ? The full URL Like http://192.168.1.15:8443/config ?

**Comment by jeremywillans** [comment]
Are you running docker on the same server as home assistant? It needs to be the full path to the config folder. 

If it's on a different server, then you might be better running the HA community store addon

**Comment by Tokn59** [comment]
Yes, on the same server ... So exactly like this http://192.168.1.15:8443/config.  ???

Also when starting nginx docker I get the following error :

docker run --name php-nginx -p 3001:8080 -v /192.168.1.15:8443/config/vacuum:/app -e NGINX_WEBROOT=/app webhippie/php-nginx:latest

docker: Error response from daemon: invalid mode: /app.
See 'docker run --help'.
➜  ~ 


BIG THANKS FOR YOUR HELP !!!!

**Comment by jeremywillans** [comment]
Actually... What model robot do you have? The php container isn't really needed as iRobot removed the ability to do coordinates in all the i/s/j series

**Comment by Tokn59** [comment]
I have an irobot Roomba i5 series.

**Comment by jeremywillans** [comment]
Skip the php container, not needed.

**Comment by Tokn59** [comment]
So, I best remove the nginx php server right ? And then how do I continue with the other errors ?

**Comment by Tokn59** [comment]
The rest980 container is running still ....

**Comment by jeremywillans** [comment]
Yes you can remove that container.

I suggest reviewing the configuration, specifically the entries in the secrets file

**Comment by Tokn59** [comment]
Just to be sure Jeremy, the location of secrets.yaml is in te config folder. The location of the vacuum.yaml also ?

**Comment by jeremywillans** [comment]
Secrets yes.

For the vacuum I recommend using packages feature - it's documented in the instructions

**Comment by Tokn59** [comment]
Ok, done, added the packages in configuration.yaml. I see that there are some MQTT entries ... Does this look like "generated" by the RES980 API ?

<img width="494" alt="image" src="https://github.com/user-attachments/assets/a37d09c6-e975-472f-9003-e24203376d8c">

**Comment by jeremywillans** [comment]
if issues are still persisting - suggest moving over to using https://github.com/ia74/roomba_rest980
